Repository KDT3-miniproject-team1/frontend, pull requests merged in 2023-02, with the labels that each got.

#2 Env: init project
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.tsx
  src/api/api.ts
  src/app/hooks.ts
  src/app/store.ts
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-ExtraBold.woff2
  src/assets/fonts/Pretendard-ExtraLight.woff2
  src/assets/fonts/Pretendard-Light.woff2
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/fonts/Pretendard-Thin.woff2
  src/assets/fonts/fonts.css
  src/components/layout/Layout.tsx
  src/constants/colors.ts
  src/features/testSlice/testSlice.ts
  src/global/css.css
  src/global/globalStyles.ts
  src/index.tsx
  src/pages/Cart.tsx
  src/pages/Likes.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/ProductDetail.tsx
  src/pages/Search.tsx
  src/pages/SignIn.tsx
  src/pages/SingUp.tsx
  src/react-app-env.d.ts
  src/router/Router.tsx
  tsconfig.json
Labels: enhancement

#3 Docs: 이슈, 풀리퀘 템플릿 추가
  .github/issue_template.md
  .github/pull_request_template.md
  README.md
Labels: documentation

#4 Feature
  src/constants/colors.ts
  src/global/globalStyles.ts
  src/pages/NotFound.tsx
  src/pages/Order.tsx
  src/router/Router.tsx
Labels: enhancement

#14 Feat: 마이페이지 ui 진행중
  src/components/myPage/FemaleAvatar.tsx
  src/components/myPage/MaleAvatar.tsx
  src/global/globalStyles.ts
  src/pages/MyPage.tsx
  src/pages/User.tsx
  src/router/Router.tsx
Labels: enhancement

#18 Feat: 메인 태그 패딩추가, 폰트 글로벌로 관리
  src/components/layout/Layout.tsx
  src/constants/colors.ts
  src/global/fonts.css
  src/global/globalStyles.ts
  src/index.tsx
Labels: Feat

#21 Feat: 헤더 완료
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/layout/Layout.tsx
Labels: Feat

#23 Feat: 마이페이지 회원정보 수정 ui, 유효성 검증 진행중
  .eslintrc.json
  package-lock.json
  package.json
  src/pages/User.tsx
Labels: Feat, work in progress

#27 Feat: 헤더 수정 및 메인 완료 (비회원용)
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/layout/Layout.tsx
  src/components/mainContent/recommendList.tsx
  src/data/listData.json
  src/global/globalStyles.ts
  src/pages/Main.tsx
  src/pages/Search.tsx
Labels: enhancement, Feat

#26 로그인 페이지 작업 완료
  src/components/auth/InputModule.tsx
  src/components/auth/StyledUtils.tsx
  src/global/FigmaStyles.tsx
  src/pages/SignIn.tsx
Labels: Feat

#35 Feat: ItemList 컴포넌트 생성
  src/components/ItemList.tsx
  src/pages/Main.tsx
Labels: enhancement, Feat

#33 Feat: 인풋 컴포넌트 분리, 폼 컴포넌트 생성, 마이페이지 공통 레이아웃 추가
  src/components/layout/MypageLayout.tsx
  src/components/myPage/Button.tsx
  src/components/myPage/Header.tsx
  src/components/myPage/TextFiled.tsx
  src/components/myPage/UserForm.tsx
  src/pages/MyPage.tsx
  src/pages/User.tsx
  src/router/Router.tsx
Labels: Feat

#36 Feat: 관심 상품 ui, 스켈레톤 진행중
  src/components/SkeletonUi.tsx
  src/pages/Likes.tsx
  src/pages/MyPage.tsx
Labels: Feat, work in progress

#37 Feat: 검색 페이지 && 탭
  src/components/Footer.tsx
  src/components/Header.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
Labels: enhancement, Feat

#44 Feat: 탭 수정 완료
  src/components/Footer.tsx
Labels: Feat

#49 Feat: 404 페이지 마크업
  src/components/svg/FemaleAvatar.tsx
  src/components/svg/MaleAvatar.tsx
  src/components/svg/NotFoundIcon.tsx
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
Labels: Feat

#40 회원 가입 페이지 추가
  .gitignore
  src/components/auth/CheckBoxButton.tsx
  src/components/auth/InputModule.tsx
  src/components/auth/SecurityNumberInput.tsx
  src/components/layout/GotoBackLayout.tsx
  src/global/FigmaStyles.tsx
  src/global/globalStyles.ts
  src/pages/SignIn.tsx
  src/pages/SingUp.tsx
  src/router/Router.tsx
Labels: Feat

#51 Feat: 탭 오류 수정 및 회원용 메인 페이지 마크업
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/components/ItemList.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
Labels: enhancement, Feat

#50 Feat: 장바구니 헤더 추가
  package-lock.json
  src/components/ItemList.tsx
  src/components/cart/CartHeader.tsx
  src/components/cart/CartItem.tsx
  src/pages/Cart.tsx
  src/pages/CompleteOrder.tsx
  src/pages/Likes.tsx
  src/pages/Main.tsx
  src/router/Router.tsx
Labels: Feat

#55 Feat: 비밀번호 확인 페이지 생성
  .gitignore
  package.json
  src/components/myPage/TextFiled.tsx
  src/components/myPage/UserForm.tsx
  src/pages/MyPage.tsx
  src/pages/Password.tsx
  src/pages/SingUp.tsx
  src/router/Router.tsx
Labels: Feat

#60 Feat: react query provider, devtool 추가
  package-lock.json
  package.json
  src/api/api.ts
  src/index.tsx
Labels: Feat

#61 Refactor: root layout 수정
  src/components/ItemList.tsx
  src/components/SkeletonUi.tsx
  src/components/layout/Footer.tsx
  src/components/layout/GotoBackLayout.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/MypageLayout.tsx
  src/components/layout/PageHeader.tsx
  src/components/myPage/Header.tsx
  src/pages/Cart.tsx
  src/router/Router.tsx
Labels: Feat

#63 Feat: 프로젝트 이름 추가
  public/index.html
  src/components/layout/Header.tsx
  src/components/layout/PageHeader.tsx
Labels: Feat

#65 Feat: 페이지 네이션
  package-lock.json
  package.json
  src/components/ItemList.tsx
  src/components/Pagination.tsx
  src/components/layout/Header.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
Labels: enhancement

#67 Feat: 장바구니 api 추가
  src/api/carts.ts
  src/components/ItemList.tsx
  src/components/productDetail/LoanInterest.tsx
  src/data/listData.json
  src/pages/Cart.tsx
  src/pages/CompleteOrder.tsx
  src/pages/Main.tsx
  src/pages/ProductDetail.tsx
  src/pages/SingUp.tsx
Labels: Feat

#70 Feat: 관심상품, 주문내역 api 함수 생성 , 아이템 타입 추가
  src/api/api.ts
  src/api/likes.ts
  src/api/orders.ts
  src/api/user.ts
  src/components/ItemList.tsx
  src/pages/Likes.tsx
  src/pages/NotFound.tsx
  src/types/itemType.ts
Labels: Feat, work in progress

#73 Feat: 검색, 비회원용 메인 추천 api 연결
  src/api/main.ts
  src/api/search.ts
  src/components/ItemList.tsx
  src/components/Pagination.tsx
  src/pages/Cart.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/types/itemType.ts
Labels: Feat

#81 Feat: 검색 리스트 드롭다운 정렬
  src/api/api.ts
  src/api/main.ts
  src/api/search.ts
  src/components/ItemList.tsx
  src/components/dropDown.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
Labels: enhancement

#83 Feature/bang jun woo
  package-lock.json
  package.json
  src/Loading.tsx
  src/app/store.ts
  src/components/auth/CheckBoxButton.tsx
  src/hooks/useLoginAxios.tsx
  src/pages/SignIn.tsx
  src/pages/SingUp.tsx
  src/reducers/auth.tsx
Labels: Feat

#84 Feat: 장바구니 추가/삭제, 상세페이지 api
  src/api/carts.ts
  src/api/productDetail.ts
  src/components/ItemList.tsx
  src/components/cart/OrderModal.tsx
  src/data/productData.json
  src/hooks/useCart.tsx
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
  src/pages/SingUp.tsx
  src/types/itemType.ts
Labels: Feat

#85 Feat: 마이페이지 작업중
  src/api/user.ts
  src/app/store.ts
  src/components/myPage/Button.tsx
  src/components/myPage/TextFiled.tsx
  src/components/myPage/UserForm.tsx
  src/features/authSlice.tsx
  src/features/testSlice/testSlice.ts
  src/pages/Likes.tsx
  src/pages/Order.tsx
  src/pages/Password.tsx
  src/pages/SignIn.tsx
  src/pages/SingUp.tsx
Labels: work in progress

#90 Feat: 가입목적 수정 및 맞춤 추천 구분
  src/api/carts.ts
  src/api/main.ts
  src/api/search.ts
  src/components/ItemList.tsx
  src/pages/Main.tsx
  src/pages/Search.tsx
  src/pages/SingUp.tsx
Labels: Feat

#91 persist 와 , 퍼시스트 로딩 추가
  src/PageLoading.tsx
  src/app/store.ts
  src/index.tsx
  src/pages/SingUp.tsx
Labels: Feat

#92 fix : 잘못된 머지 수정
  src/components/auth/SecurityNumberInput.tsx
  src/pages/SingUp.tsx
Labels: bug

#94 Feature: useCart 훅 생성
  src/api/carts.ts
  src/api/likes.ts
  src/api/orders.ts
  src/api/productDetail.ts
  src/api/search.ts
  src/components/ItemList.tsx
  src/components/cart/OrderModal.tsx
  src/components/productDetail/CartModal.tsx
  src/hooks/useCart.tsx
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
  src/types/itemType.ts
Labels: Feat

#96 Refactor: redux persist 오류 수정 및 로딩 페이지 삭제
  src/PageLoading.tsx
  src/app/store.ts
  src/features/authSlice.tsx
  src/index.tsx
Labels: Feat

#97 Feat: 메인 페이지 오류 수정
  src/api/main.ts
  src/pages/Main.tsx
Labels: Feat

#98 Feat: api interceptors 추가 권한별 라우팅
  src/api/api.ts
  src/components/layout/PageHeader.tsx
  src/router/PrivateRouter.tsx
  src/router/PublicRouter.tsx
  src/router/Router.tsx
Labels: work in progress

#100 Feat: 회원 정보 로컬스토리지 연결 완료
  src/api/main.ts
  src/components/layout/Footer.tsx
  src/pages/Main.tsx
  src/types/itemType.ts
Labels: Feat

#101 Feat: 모달창 수정, 예외 처리
  src/api/carts.ts
  src/api/orders.ts
  src/components/ItemList.tsx
  src/components/productDetail/LoanInterest.tsx
  src/hooks/useCart.tsx
  src/pages/Cart.tsx
  src/pages/ProductDetail.tsx
Labels: Feat

#102 Feat: 메인 오류 수정
  src/api/main.ts
  src/components/layout/Footer.tsx
  src/pages/Main.tsx
Labels: Feat

#108 Feat: api 수정중, 관심상품 구현
  src/api/api.ts
  src/api/carts.ts
  src/api/likes.ts
  src/api/main.ts
  src/api/orders.ts
  src/api/productDetail.ts
  src/api/search.ts
  src/app/store.ts
  src/features/likeSlice.tsx
  src/hooks/useLoginAxios.tsx
  src/pages/Likes.tsx
  src/pages/Main.tsx
  src/pages/ProductDetail.tsx
  src/router/Router.tsx
Labels: work in progress

#112 요청 데이터 수정, 회원 정보 로직 구현중..
  README.md
  public/index.html
  src/api/api.ts
  src/api/user.ts
  src/components/myPage/UserForm.tsx
  src/pages/MyPage.tsx
  src/pages/Password.tsx
  src/pages/SignIn.tsx
  src/pages/SingUp.tsx
  src/pages/User.tsx
Labels: work in progress

#113 Feat: 회원정보 관련 api 작업 진행중
  src/api/user.ts
  src/components/myPage/TextFiled.tsx
  src/components/myPage/UserForm.tsx
  src/features/authSlice.tsx
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/Password.tsx
  src/pages/ProductDetail.tsx
  src/pages/User.tsx
Labels: work in progress

#115 Refactor: 유저 관리 리덕스로, 회원가입 후 로그인 페이지로 이동
  src/pages/Main.tsx
  src/pages/MyPage.tsx
  src/pages/SingUp.tsx
Labels: work in progress
